import type { LeaderboardEntry, Submission } from './types'

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    model: 'claude-opus-4.5',
    provider: 'anthropic',
    total_score: 9.2,
    max_score: 10.0,
    percentage: 92.0,
    timestamp: '2026-02-10T15:30:00Z',
    submission_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  },
  {
    rank: 2,
    model: 'gpt-4.5',
    provider: 'openai',
    total_score: 8.7,
    max_score: 10.0,
    percentage: 87.0,
    timestamp: '2026-02-09T10:15:00Z',
    submission_id: 'b2c3d4e5-f6a7-8901-bcde-f23456789012',
  },
  {
    rank: 3,
    model: 'claude-sonnet-4',
    provider: 'anthropic',
    total_score: 8.1,
    max_score: 10.0,
    percentage: 81.0,
    timestamp: '2026-02-10T08:45:00Z',
    submission_id: 'c3d4e5f6-a7b8-9012-cdef-123456789abc',
  },
  {
    rank: 4,
    model: 'gpt-4.5-turbo',
    provider: 'openai',
    total_score: 7.9,
    max_score: 10.0,
    percentage: 79.0,
    timestamp: '2026-02-08T14:20:00Z',
    submission_id: 'd4e5f6a7-b8c9-0123-def4-56789abcdef0',
  },
  {
    rank: 5,
    model: 'gemini-2.0-ultra',
    provider: 'google',
    total_score: 7.5,
    max_score: 10.0,
    percentage: 75.0,
    timestamp: '2026-02-07T16:55:00Z',
    submission_id: 'e5f6a7b8-c9d0-1234-ef56-789abcdef012',
  },
]

export const mockSubmissions: Record<string, Submission> = {
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890': {
    submission_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    model: 'claude-opus-4.5',
    provider: 'anthropic',
    timestamp: '2026-02-10T15:30:00Z',
    openclaw_version: '2.1.0',
    total_score: 9.2,
    max_score: 10.0,
    metadata: {
      run_timestamp: 1707577800,
      task_count: 10,
    },
    task_results: [
      {
        task_id: 'task_01_calendar',
        task_name: 'Calendar Event Creation',
        category: 'calendar',
        score: 1.0,
        max_score: 1.0,
        grading_type: 'automated',
        breakdown: {
          file_created: 1.0,
          date_correct: 1.0,
          time_correct: 1.0,
          attendee_present: 1.0,
          title_correct: 1.0,
          description_present: 1.0,
        },
        timed_out: false,
      },
      {
        task_id: 'task_02_stock_research',
        task_name: 'Stock Price Research',
        category: 'research',
        score: 0.9,
        max_score: 1.0,
        grading_type: 'automated',
        breakdown: {
          api_called: 1.0,
          data_extracted: 1.0,
          format_correct: 0.7,
        },
        timed_out: false,
      },
      {
        task_id: 'task_03_blog_post',
        task_name: 'Blog Post Writing',
        category: 'writing',
        score: 0.95,
        max_score: 1.0,
        grading_type: 'llm_judge',
        breakdown: {
          structure: 1.0,
          coherence: 1.0,
          grammar: 0.9,
          engagement: 0.9,
        },
        timed_out: false,
      },
      {
        task_id: 'task_04_weather',
        task_name: 'Weather Script Creation',
        category: 'coding',
        score: 1.0,
        max_score: 1.0,
        grading_type: 'automated',
        breakdown: {
          script_created: 1.0,
          api_called: 1.0,
          output_formatted: 1.0,
        },
        timed_out: false,
      },
      {
        task_id: 'task_05_document_summary',
        task_name: 'Document Summarization',
        category: 'comprehension',
        score: 0.85,
        max_score: 1.0,
        grading_type: 'llm_judge',
        breakdown: {
          key_points: 0.9,
          accuracy: 0.9,
          conciseness: 0.8,
          completeness: 0.8,
        },
        timed_out: false,
      },
      {
        task_id: 'task_06_context_retrieval',
        task_name: 'Memory Retrieval',
        category: 'context',
        score: 1.0,
        max_score: 1.0,
        grading_type: 'automated',
        breakdown: {
          correct_recall: 1.0,
          context_used: 1.0,
        },
        timed_out: false,
      },
      {
        task_id: 'task_07_file_operations',
        task_name: 'File Operations',
        category: 'coding',
        score: 0.9,
        max_score: 1.0,
        grading_type: 'automated',
        breakdown: {
          files_created: 1.0,
          content_correct: 0.8,
        },
        timed_out: false,
      },
      {
        task_id: 'task_08_multi_step',
        task_name: 'Multi-step Workflow',
        category: 'complex',
        score: 0.8,
        max_score: 1.0,
        grading_type: 'hybrid',
        breakdown: {
          step_1: 1.0,
          step_2: 0.9,
          step_3: 0.7,
          integration: 0.7,
        },
        timed_out: false,
      },
      {
        task_id: 'task_09_email_draft',
        task_name: 'Email Drafting',
        category: 'writing',
        score: 0.9,
        max_score: 1.0,
        grading_type: 'llm_judge',
        breakdown: {
          tone: 0.9,
          clarity: 0.9,
          professionalism: 0.9,
        },
        timed_out: false,
      },
      {
        task_id: 'task_10_tech_events',
        task_name: 'Tech Events Research',
        category: 'research',
        score: 0.9,
        max_score: 1.0,
        grading_type: 'automated',
        breakdown: {
          events_found: 0.9,
          details_correct: 0.9,
        },
        timed_out: false,
      },
    ],
  },
}
